// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
//
// NOTE: The client is intentionally untyped at the PostgREST layer. Domain
// types (Product, Order, etc.) from ./types are applied explicitly at each
// call site (e.g. `data as Product[]`). This avoids the strict GenericSchema
// constraints of supabase-js v2.90 collapsing insert/update payloads to
// `never` when using a hand-authored Database type.
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});